In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 832.7 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.4 MB 951.0 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.4 MB 951.0 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.4 MB 951.0 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.4 MB 702.2 kB/s eta 0:00:17
   --- ------------------------------------ 1.0/12.4 MB 702.2 kB/s eta 0:00:17
   ---- ----------------------------


[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
#1d array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2d array
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
#zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#Random
np.random.rand(3)

array([0.62896964, 0.56671939, 0.87803327])